### ISSUE TITLE
Bad installation instructions

### ISSUE THREAD

**Issue by aiwilliams** [othree/html5-syntax.vim#1]
Using the `curl http://github.com/othree/html5-syntax.vim/raw/master/syntax/html.vim > ~/.vim/syntax/html.vim` no workey when multiple files, particularly because the file is not found.

**Comment by othree** [comment]
You can use [html5.vim](https://github.com/othree/html5.vim) instead :)
Which I pay more attention on it. And better support for multiple files.

I will fix this later.
